### PR TITLE
Aigerim

### PR DESCRIPTION
**Pull request by seytechdevops**
Creating PR(Pull Request) from Aigerim to main branch

### CODE REVIEW

**Review by tlektess — APPROVED** [review]

**Review by kabbatyr — APPROVED** [review]

**Comment by Dina148** [comment]
Hi Aigerim, looks good you can merge it ti main

**Comment by Botagoz-star** [comment]
ok nice job

**Review by ilnura-it — APPROVED** [review]

**Comment by kabbatyr** [comment]
👍👍👍

**Comment by omurkanovmirbek** [comment]
good job

**Review by aidar1009 — APPROVED** [review]

**Review by Dina148 — APPROVED** [review]

**Review by Botagoz-star — APPROVED** [review]

**Pull request merged**
